# Javascript Node CircleCI 2.0 configuration file

# Build and run test suite
build-job:
  docker:
    - image: circleci/node:10.9

  working_directory: ~/platform

  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - run: 
        name: Install Dependencies
        command: npm install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    # run tests!
    - run: 
        name: Test Suite
        command: npm test

# Deploy to Firebase
deploy-job:
  docker: 
    - image: circleci/node:10.9

  working_directory: ~/platform

  steps:
    - run:
        name: Deploy to Firebase
        command: npm run deploy

workflows:
  version: 2

  -deploy:
    jobs:
      - build-job
      - deploy-job:
          context: Firebase
          requires:
            - build-job
          filters:
            branches:
              only: master
