# Javascript Node CircleCI 2.0 configuration file

version: 2

jobs:
  # Build and run test suite
  build:
    docker:
      - image: circleci/node:10.9

    working_directory: ~/platform

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: 
          name: Test Suite
          command: npm test

  # Deploy to Firebase
  deploy:
    docker: 
      - image: circleci/node:10.9

    working_directory: ~/platform

    steps:
      - run:
          name: Deploy to Firebase
          command: npm run deploy

workflows:
  version: 2

  -deploy:
    jobs:
      - build
      - deploy:
          context: Firebase
          requires:
            - build
          filters:
            branches:
              only: master
