# Javascript Node CircleCI 2.0 configuration file

defaults: &defaults
  working_directory: ~/platform
  docker:
    - image: circleci/node:10.9

version: 2
jobs:
  # Build and run test suite
  build:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build
      - persist_to_workspace:
          root: ~/platform
          paths:
            - dist
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/platform
      - run:
          name: Test Suite
          command: npm test

  # Deploy to Firebase
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/platform
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - build
      - test:
        requires:
          - build
      - deploy:
          context: Firebase
          requires:
            - test
          filters:
            branches:
              only: master
