# Javascript Node CircleCI 2.0 configuration file

version: 2
jobs:
  build:
    working_directory: ~/platform
    docker:
      - image: circleci/node:10.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build
      - persist_to_workspace:
          root: ~/platform
          paths:
            - dist
            - node_modules
  test:
    working_directory: ~/platform
    docker:
      - image: circleci/node:10.9
    steps:
      - checkout
      - attach_workspace:
          at: ~/platform
      - run:
          name: Test Suite
          command: npm test
  deploy:
    working_directory: ~/platform
    docker:
      - image: circleci/node:10.9
    steps:
      - checkout
      - attach_workspace:
          at: ~/platform
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          context: Firebase
          requires:
            - test
          filters:
            branches:
              only: master
